// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: addLastFetchedAt.sql

package database

import (
	"context"
)

const addLastFetchedAt = `-- name: AddLastFetchedAt :exec
ALTER TABLE feeds
ADD COLUMN last_fetched_at TIMESTAMP
`

func (q *Queries) AddLastFetchedAt(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, addLastFetchedAt)
	return err
}
