// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: createUsers.sql

package database

import (
	"context"
)

const createUsers = `-- name: CreateUsers :exec
CREATE TABLE users(id UUID PRIMARY KEY,created_at TIMESTAMP NOT NULL,updated_at TIMESTAMP NOT NULL, name TEXT UNIQUE NOT NULL)
`

func (q *Queries) CreateUsers(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, createUsers)
	return err
}
