// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: createFeeds.sql

package database

import (
	"context"
)

const createFeeds = `-- name: CreateFeeds :exec
CREATE TABLE feeds(id UUID PRIMARY KEY,created_at TIMESTAMP NOT NULL,updated_at TIMESTAMP NOT NULL, name TEXT UNIQUE NOT NULL, url TEXT UNIQUE NOT NULL, user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE)
`

func (q *Queries) CreateFeeds(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, createFeeds)
	return err
}
