// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: createPosts.sql

package database

import (
	"context"
)

const createPosts = `-- name: CreatePosts :exec
CREATE TABLE posts(
    id UUID PRIMARY KEY,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    title TEXT UNIQUE NOT NULL,
    url TEXT UNIQUE NOT NULL,
    description TEXT,
    published_at TIMESTAMP NOT NULL,
    feed_id UUID NOT NULL REFERENCES feeds(id)
)
`

func (q *Queries) CreatePosts(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, createPosts)
	return err
}
