// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: createFeedFollows.sql

package database

import (
	"context"
)

const createFeedFollows = `-- name: CreateFeedFollows :exec
CREATE TABLE feed_follows(
    id UUID PRIMARY KEY,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL, 
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    feed_id UUID NOT NULL REFERENCES feeds(id) ON DELETE CASCADE)
`

func (q *Queries) CreateFeedFollows(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, createFeedFollows)
	return err
}
