// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: dropFeedFollows.sql

package database

import (
	"context"
)

const dropFeedFollows = `-- name: DropFeedFollows :exec
DROP TABLE feed_follows
`

func (q *Queries) DropFeedFollows(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, dropFeedFollows)
	return err
}
