// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: dropFeeds.sql

package database

import (
	"context"
)

const dropFeeds = `-- name: DropFeeds :exec
DROP TABLE feeds
`

func (q *Queries) DropFeeds(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, dropFeeds)
	return err
}
