// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: dropLastFetchedAt.sql

package database

import (
	"context"
)

const dropLastFetchedAt = `-- name: DropLastFetchedAt :exec
ALTER TABLE feeds
DROP COLUMN last_fetched_at
`

func (q *Queries) DropLastFetchedAt(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, dropLastFetchedAt)
	return err
}
