// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: dropUsers.sql

package database

import (
	"context"
)

const dropUsers = `-- name: DropUsers :exec
DROP TABLE users
`

func (q *Queries) DropUsers(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, dropUsers)
	return err
}
