// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: dropPosts.sql

package database

import (
	"context"
)

const dropPosts = `-- name: DropPosts :exec
DROP TABLE posts
`

func (q *Queries) DropPosts(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, dropPosts)
	return err
}
