// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: getUserFeeds.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getUserFeeds = `-- name: GetUserFeeds :many
WITH feedfollows AS (
    SELECT id, created_at, updated_at, user_id, feed_id FROM feed_follows
    WHERE feed_follows.user_id = $1
)
SELECT 
    feedfollows.id, feedfollows.created_at, feedfollows.updated_at, feedfollows.user_id, feedfollows.feed_id,
    feeds.name AS feed_name,
    users.name AS user_name
FROM feedfollows
INNER JOIN feeds ON feedfollows.feed_id = feeds.id
INNER JOIN users ON feedfollows.user_id = users.id
`

type GetUserFeedsRow struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    uuid.UUID
	FeedID    uuid.UUID
	FeedName  string
	UserName  string
}

func (q *Queries) GetUserFeeds(ctx context.Context, userID uuid.UUID) ([]GetUserFeedsRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserFeeds, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserFeedsRow
	for rows.Next() {
		var i GetUserFeedsRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
			&i.FeedID,
			&i.FeedName,
			&i.UserName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
