// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: getUserFeeds.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getUserFeeds = `-- name: GetUserFeeds :many
WITH feedfollows AS (
    SELECT id, created_at, updated_at, user_id, feed_id FROM feed_follows
    WHERE feed_follows.user_id = $1
)
SELECT 
    feeds.id,
    feeds.created_at,
    feeds.updated_at,
    feeds.name,
    feeds.url,
    feeds.user_id,
    feeds.last_fetched_at
FROM feedfollows
INNER JOIN feeds ON feedfollows.feed_id = feeds.id
INNER JOIN users ON feedfollows.user_id = users.id
`

func (q *Queries) GetUserFeeds(ctx context.Context, userID uuid.UUID) ([]Feed, error) {
	rows, err := q.db.QueryContext(ctx, getUserFeeds, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Feed
	for rows.Next() {
		var i Feed
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Name,
			&i.Url,
			&i.UserID,
			&i.LastFetchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
